### PR TITLE
Use Closure Compiler directly instead of closurebuilder.py.

### PR DESCRIPTION
**Pull request by kjin**
This changes the libphonenumber `compile-*` commands to use Closure Compiler instead of `closurebuilder.py`. `closurebuilder.py` is an old wrapper around Closure Compiler, and will be deleted from the Closure Library repository soon. It even emits a warning saying that [Closure Compiler should be used directly instead](https://github.com/google/closure-library/blob/7d07947d3f1e8a9a10626d9b57a10f793c2f96a7/closure/bin/build/closurebuilder.py#L263-L271).

No functional changes are expected.

### CODE REVIEW

**Comment by penmetsaa** [comment]
Hi,

Thanks much for the fixes. Could you please add require statements for these packages i18n.phonenumbers.PhoneNumberType and PhoneNumberFormat in file: phonenumberutil_test.js?

I am not sure if this is ramification of this fix. However witthout this we were not able to compile the tests.
$ ant -f javascript/build.xml compile
>>      [exec] i18n/phonenumbers/phonenumberutil_test.js:3811:30: ERROR - [JSC_MISSING_REQUIRE_IN_PROVIDES_FILE] 'i18n.phonenumbers.PhoneNumberFormat' references a namespace which was not required by this file.
.
.

**Comment by kjin** [comment]
@penmetsaa Yep, I've fixed it! The compilation should succeed now.

**Comment by kjin** [comment]
As for the lint target not working, I can't repro it at the moment. I don't think I touched anything that would cause it to behave differently. Does it still work when you run the command on `master`?

**Comment by penmetsaa** [comment]
Hi,

I have picked the latest updates from your fork, and getting below errors when try compiling demo and tests.

>>$ ant compile-demo
Buildfile: /usr/local/google/home/penmetsaa/github_lab/libphonenumber/javascript/build.xml
compile-demo:
    [exec] i18n/phonenumbers/shortnumberinfo_test_BASE_1065575.js:32:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "i18n.phonenumbers.RegionCode" never defined.
     [exec]   32| goog.require('i18n.phonenumbers.RegionCode');
     [exec]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec] 
     [exec] 1 error(s), 0 warning(s)

>>$ ant compile-tests
Buildfile: /usr/local/google/home/penmetsaa/github_lab/libphonenumber/javascript/build.xml
nul:
devnull:
setnulldevice:
compile-tests:
     [exec] i18n/phonenumbers/asyoutypeformatter_test.js:34:4: ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable RegionCode declared more than once. First occurrence: i18n/phonenumbers/shortnumberinfo_test_BASE_1065575.js
     [exec]   34| var RegionCode = i18n.phonenumbers.RegionCode;
     [exec]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec] 
     [exec] 1 error(s), 0 warning(s)
BUILD FAILED
/usr/local/google/home/penmetsaa/github_lab/libphonenumber/javascript/build.xml:110: The following error occurred while executing this line:
/usr/local/google/home/penmetsaa/github_lab/libphonenumber/javascript/build.xml:22: exec returned: 1
Total time: 9 seconds

I am not clueless how this package `i18n.phonenumbers.RegionCode` is picked all these days; we deliberately do not want to load the one declared in `i18n/phonenumbers/regioncodefortesting.js`, as we want the live regionocode list. Presently we do not have JS experise who can look into this; please help.

@Lint error,
Yes, I am am able to reproduce at the master branch as well. So not a ramification of present changes.

**Comment by kjin** [comment]
What is `i18n/phonenumbers/shortnumberinfo_test_BASE_1065575.js`? The errors seem to be reported for this file, but it doesn't seem to be part of the repo. Can you try removing it and compiling it again?

> I am not clueless how this package i18n.phonenumbers.RegionCode is picked all these days; we deliberately do not want to load the one declared in i18n/phonenumbers/regioncodefortesting.js, as we want the live regionocode list.

I believe this file is still being excluded, at least in the demo. The `!` in `--js="!i18n/phonenumbers/regioncodefortesting.js"` indicates that the file is excluded. So as far as I can tell, I don't think this is the cause.

**Comment by penmetsaa** [comment]
True.. I have not realised that. Thanks much :)
We are good to go with this PR.

**Review by penmetsaa — APPROVED** [review]

**Comment by kjin** [comment]
Ok, thanks! :)

**Comment by kissifrot** [comment]
Hello @kjin , I'm just having a little question: which version of google closure compiler did you use to build the demo? The version I'm using (v20210601) adds eval() to the generated code which cause CSP errors when testing.

**Pull request merged**
