### PR TITLE
Accelerate SimpleItoa conversion using abseil function

### PR DESCRIPTION
**Pull request by gvollant**
After reading comment from @katbohm and @penmetsaa on #2703 and #2711, I created this PR for faster itoa.

Using abseil function, SimpleItoa create less several temporary object than previous version and give speed improvement

### CODE REVIEW

**Comment by gvollant** [comment]
@katbohm and @penmetsaa , do you known this "style" of modification correct with libphone rule?

regards

**Comment by penmetsaa** [comment]
Hi @gvollant ,

Thanks so much for the understanding the status quo of maintaing an open source library :)
We appreciate your contributions for improving our CPP port.

This change looks good to me. I am in process of doing further improvements, mainly towards
use of abseil packages.
Still a draft version: https://github.com/google/libphonenumber/pull/2734

**Review by penmetsaa — APPROVED** [review]

**Comment by gvollant** [comment]
Thank you.
I'm curious to known if you have speed enhancement with this modification

**Comment by penmetsaa** [comment]
Hi @gvollant 
No we have not checked that..
We are just streamling the packages on what we depeneding on.
Is there any quick way that I can do benchmark testing?

**Comment by gvollant** [comment]
One of my batch take 61 seconds instead 65 seconds.

I had more speed enhanchement with c++17 std::to_chars

**Comment by penmetsaa** [comment]
Oh ok...
I think we are now operating at c++11 as min standard.
Maybe, it will be hard for other users as they need to recompile at c++17?
We generally discourage any forceful rebuild unless we have reasons; here,
as we mentioned earlier we are opting for consistency in using the utils.

Once my changes were done, maybe you help us by running the batch again.
I will check other team's CPP expert and conclude on approach, if performance
got hit badly.
P.S: We presently do not have CPP expert in team. Thanks for your help here.

**Comment by gvollant** [comment]
And what about a choice between c++11 and c++17 as cmake parameter, then use std::to_chars is c++17 is detected?

**Comment by penmetsaa** [comment]
Hi @gvollant ,
As of now, we cannot migrate to c++17 for above mentioned reasons.
Please let us know if you think otherwise.

**Comment by gvollant** [comment]
I just suggest adding a "c++ version" option in the Cmake argument.
By default, we compile using c++11
If user select c++17, we can use c++17 feature

**Comment by penmetsaa** [comment]
Hi,

Oh ok...
If the change do not force users to recompile at C++17, we are OK with it.
Please confirm my understanding: The api std::to_chars will direct to older implementations if C++17 is not present.
If yes, I have a PR in review, please help with a new PR after that: https://github.com/google/libphonenumber/pull/2734/files

P.S:
I am no CPP expert, please correct if I am wrong anywhere.
Please share your feedback on my PR. :)

**Pull request merged**
