### PR TITLE
libphonernumber 25% speed improvement by SimpleItoa function

### PR DESCRIPTION
**Pull request by gvollant**
the function SimpleItoa create several temporary object.

This small modification use code from @jeaiii , project https://github.com/jeaiii/itoa , under MIT licence.

There is a 25% speed improvement without additionnal dependency or compatibility requirement

### CODE REVIEW

**Comment by gvollant** [comment]
Before merging, we need add acknoledgement to James Edward Anhalt III on CONTRIBUTORS and/or pehaps other files

**Comment by gvollant** [comment]
@penmetsaa if you want speed improvement :-)

**Comment by penmetsaa** [comment]
Sure.. We will triage/review on this.
However, metadata updates are the priority for us to ensure the data is fresh.
We will get to this as soon as we have some free time.

**Comment by gvollant** [comment]
> Sure.. We will triage/review on this. However, metadata updates are the priority for us to ensure the data is fresh. We will get to this as soon as we have some free time.

the other option is code from https://github.com/google/libphonenumber/pull/2703#issuecomment-1002339155 , but we need option to compile libphone with c++17

**Comment by katbohm** [comment]
Hi @gvollant, thank you for the proposed changes. However, as Aravind (#2703) mentioned, our intention is to go away from the String util implementations like this, replacing them with more functionality from absl packages. Thus, we currently won't be able to accept alternative implementations PRs like this one.

**Comment by gvollant** [comment]
What is the solution to replace current SimpleItoa which take a lot of time?
I don't find an itoa like fast function in abeil

Pehaps the solution if offering option to compile with C++17 and use std::from_chars

**Comment by katbohm** [comment]
Yes, replacing it with absl::StrCat is what I had in mind -- as you did in [#2731](https://github.com/google/libphonenumber/pull/2731) -- thank you for your contributions!

**Pull request closed without merging**
