### PR TITLE
Update the Netherlands (NL) section

### PR DESCRIPTION
**Pull request by PieterGit**
*   Country: Netherlands (NL)
*   Example number(s) and/or range(s): +3197012345678
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   Where or whom did you get the number(s) from: government, https://wetten.overheid.nl/BWBR0010198/2020-04-04 
*   Authoritative evidence (e.g. national numbering plan, operator announcement): https://wetten.overheid.nl/BWBR0010198/2020-04-04 (see Appendix 1, in Dutch "Bijlage 1")
*   Link from demo (http://libphonenumber.appspot.com) showing error: https://libphonenumber.appspot.com/phonenumberparser?number=%2B3197012341234&country=NL (it shows `isPossibleNumber()==false` and `TOO_LONG` which is invalid. These number are also used for H2H communication (data, sms and/or voice).

Changes in this PR:
* update links to more recent and secure versions of wiki / government information
* update comments for 06[1-58], 067[0-5], 0970
* add 0970 numbers (12 digits) since they are also available for Human to Human (H2H) communication

This is an attempt to fix the following (Signal) issues: 
* https://github.com/signalapp/Signal-iOS/issues/4442
* https://github.com/signalapp/Signal-Android/issues/9005
* https://issuetracker.google.com/issues/140508060

Note 0970 are used for data, voice (H2H, M2H), and sms communication. Their usage depends on the telecom operator.

Please be gentle with me, since this is my first PR for this project.

### CODE REVIEW

**Comment by DrMattFaulkner** [comment]
+1

Any feedback on when this is likely to merge?

**Comment by killdashnine** [comment]
+1 any update on this?

**Comment by MeisterMasi** [comment]
+1 any updates?

**Comment by Coastcrawler** [comment]
+1 any update or even a merge would be highly appreciated

**Comment by henriAbel** [comment]
+1 any updates?

**Comment by ActiveB1t** [comment]
+1 Would like to know if there's any progress being made to merge this in an effort to stop the exclusion of a segment of Dutch mobile service users.

**Comment by lararennie** [comment]
Hi all,

Thanks Pieter for the detailed research here! Unfortunately there were no assignees nor reviewers, so no one saw this - until today when it was on the discussion list :)

Unfortunately, this PR won't be merged for two reasons:
a) Please see the contribution guidelines: PRs with validation changes are not accepted -> https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md
b) This is part of the larger issue of machine-to-machine numbering. There is an open issue about this (74493346) and discussion should happen there.

**Comment by jkr-wrk** [comment]
Why is it taking so long to fix this? And why is this closed with and issue number without a link to the actual issue? Do we need to guess where the issue is hosted?

**Comment by mahanthathreyee** [comment]
@jkr-wrk 
Here is the link to the issue [(74493346)](https://issuetracker.google.com/issues/74493346) (waiting for a solution myself)

It is mentioned in [contribution guidelines](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md)
> As of March 2018, we kindly request that you use Google's Issue Tracker to report issues with the library.

**Comment by jkr-wrk** [comment]
@mahanthathreyee Thanks. I found it there indeed. Other countries with similar issues are fixed within a month after reporting in 2019. This issue has way to little attention by the team. Please post on the issue in the other issue tracker as well because i think 
li...@google.com is not working on the issue at all. I thought it was an issue from 2019 but it is march 2018! For adding a few lines of code.

**Comment by penmetsaa** [comment]
Hi,

Sorry for being late to this thread; and sorry for not been able to make it.
I have updated the tracking issue ([74493346](https://issuetracker.google.com/issues/74493346)) the rationale and not been able to commit on fix. Till the library support the M2M ranges, we recommed clients to have workarounds in their client code itself.

**Pull request closed without merging**
