### PR TITLE
Add R library "dialr" to third party ports

### PR DESCRIPTION
**Pull request by gorcha**
[dialr](https://github.com/socialresearchcentre/dialr/) is a relatively mature R wrapper around the libphonenumber Java library (not a port as such).

### CODE REVIEW

**Comment by gorcha** [comment]
@googlebot I signed it!

**Comment by penmetsaa** [comment]
Hi,

Thanks so much for taking your time and try expanding the library's frontier.
We like to list this R port.

As we are in middle of release. Appriving now, but will merge later this week.

**Review by penmetsaa — APPROVED** [review]

**Comment by gorcha** [comment]
No worries, thanks for all the great work on libphonenumber!

**Comment by penmetsaa** [comment]
Thanks :)
Could you please update your branch?

**Comment by gorcha** [comment]
Done!

**Comment by penmetsaa** [comment]
Merge Done :)
Thanks again for all the contribution.

**Pull request merged**
