### PR TITLE
Åland Islands geo tagging

### PR DESCRIPTION
**Pull request by jonbom**
Complemented geo tagging for Åland Islands. All according to the description in http://en.wikipedia.org/wiki/+358
The official numbering plan of Finland can be found at https://www.traficom.fi/sites/default/files/media/file/Suomen_numerointisuunnitelma.pdf

### CODE REVIEW

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by jonbom** [comment]
@googlebot I fixed it.

**Comment by tvislavski** [comment]
We are so sorry this PR has gone so long undetected. Please note that as per our contribution guide, we do not accept pull requests for metadata changes (this also includes geocoding files). However, feel free to raise an issue (more info on how to do that in https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue)

**Pull request closed without merging**
