### PR TITLE
Added Ruby phonelib third-party interface

### PR DESCRIPTION
**Pull request by espen**

### CODE REVIEW

**Review by Alison090 — APPROVED** [review]

**Review by Alison090 — APPROVED** [review]

**Comment by penmetsaa** [comment]
Hi,
Thanks so much for listing your port here.
We would like to know how it is different and improvements over existing Ruby ports.

**Comment by espen** [comment]
It's not my implementation. @daddyz can perhaps answer your question.

**Comment by daddyz** [comment]
@penmetsaa It's not a fork, it implements different parsing logic based on same data.
[mini_phone](https://github.com/ianks/mini_phone) - plugs directly into Google's native C++
[telephone_number](https://github.com/mobi/telephone_number) - ruby fork based on the library
[phonelib](https://github.com/daddyz/phonelib) - is implemented with same phone parsing logic inside, but has extended functionality, it knows how to guess the country, it integrates with ActiveRecord validations, it has option to be extended by additional regexes (the ones that are not yet included in [libphonenumber](https://github.com/google/libphonenumber)). I started it 10 years ago, when there was no real way to use libphonenumber in ruby, and it grew up in separate project.

**Comment by penmetsaa** [comment]
Hi,
Thanks so much for the info.
Will merge this shortly, presently we are in middle of release cycle.

**Review by penmetsaa — APPROVED** [review]

**Pull request merged**
