### PR TITLE
Indentation formatting changes to JS sources files

### PR DESCRIPTION
**Pull request by penmetsaa**
This is done as part of cl/322862258
All JS files are compiled and tests ran successfully.

### CODE REVIEW

**Review by HimanshuP90 — COMMENTED** [review]
Hi Team, 
Recently something changed for US validation phone number because earlier this number `5551234567` is `valid true` but a couple of days we are experiencing it's valid false`?

**Comment by penmetsaa** [comment]
> 5551234567

Thanks so much for taking time to improve libphonenumber library.
Could you please raise an issue as suggested in [our contribution guidelines](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue)
Quick brief: maybe this is uplicate of https://issuetracker.google.com/issues/74518691. As this is the right place to discuss more, we can triage more on the new bug (with necessary evidences) that you would be rising.

**Comment by HimanshuP90** [comment]
@penmetsaa Thank you for quick response, I'll go through with suggested guidelines.

**Review by lararennie — APPROVED** [review]

**Comment by mv0606745-crypto** [comment]
having trouble finding location on phone here PhoneNumberUtil util = PhoneNumberUtil.createInstance(new MetadataLoader() { who can help

**Pull request merged**
