### PR TITLE
Update phonenumberutil.cc

### PR DESCRIPTION
**Pull request by carlwmsft**
Clear() must be called on the PhoneMetadata object to clear the object's allocated strings (general_desc_, fixed_line, mobile_, …)

### CODE REVIEW

**Comment by carlwmsft** [comment]
I signed it!

**Comment by gvollant** [comment]
Is this PR fix memory leak @carlwmsft  ? if yes, how to reproduce it?

**Comment by penmetsaa** [comment]
Hi,

Sorry for getting here late.
As gvollant@ mentioned could you please let us know the steps to reproduce?

Eg: The way the PhoneNumberUtil instance is deleted.. and check whether we still able to accessing this map’s secondary field pointers
So that we can see this fix has solved this issue. 

Also we are running into compilation issues, could you please make the changes accordingly?
```
phonenumberutil.cc: In destructor 'virtual i18n::phonenumbers::PhoneNumberUtil::~PhoneNumberUtil()':
phonenumberutil.cc:891:8: error: 'map' was not declared in this scope; did you mean 'std::map'?
  891 |   for (map<string, PhoneMetadata>::iterator it = region_to_metadata_map_->begin();
      |        ^~~
      |        std::map
In file included from /usr/include/c++/11/map:61,
                 from phonenumberutil.h:22,
                 from phonenumberutil.cc:15:
/usr/include/c++/11/bits/stl_map.h:100:11: note: 'std::map' declared here
  100 |     class map
      |           ^~~
phonenumberutil.cc:891:18: error: expected primary-expression before ,' token
  891 |   for (map<string, PhoneMetadata>::iterator it = region_to_metadata_map_->begin();
      |                  ^
phonenumberutil.cc:891:33: error: expected primary-expression before >' token
  891 |   for (map<string, PhoneMetadata>::iterator it = region_to_metadata_map_->begin();
      |                                 ^
phonenumberutil.cc:891:36: error: '::iterator' has not been declared; did you mean 'std::iterator'?
  891 |   for (map<string, PhoneMetadata>::iterator it = region_to_metadata_map_->begin();
      |                                    ^~~~~~~~
      |                                    std::iterator

```

**Comment by katbohm** [comment]
Hi! Thank you for your contribution.
From looking at the code, the scoped_ptr & the map it holds is created in constructor, so at/after destructor this is out of scope and gets destroyed (also the protos it hold). So I don't think this particular map is leaking, and the change proposed in this PR is not needed, I believe... If you believe otherwise, please provide us with steps to reproduce, reopen this PR, and make changes (add "std::") to fix the compilation issues. Thanks!

**Pull request closed without merging**
