### PR TITLE
Metadata updates for prefix 10,99 (AZ)

### PR DESCRIPTION
**Pull request by chz**
Added new prefixes :
1) "010" Azercell
2) "099" Bakcell

### CODE REVIEW

**Comment by chz** [comment]
@googlebot I signed it!

**Comment by chz** [comment]
@kkeshava hi. Can you review?

**Comment by vvaliyev** [comment]
@chz Thanks for adding new prefixes.

Hi, when you plan to merge this PR?

@googlebot

**Comment by kkeshava** [comment]
Hi, 
Thank you for contributing to libphonenumber! So sorry for late response.

We are not accepting pull requests for such metadata updates at this time. See our contribution guidelines: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md.

@regarding AZ issue,
This is actually working as intended; prefixes 10 and 99[2-9] are already marked by our library as  a valid *MOBILE* number. To check the latest behavior for yourself (we update metadata frequently), see the demo:
http://libphonenumber.appspot.com/phonenumberparser?number=%2B994+100123456
http://libphonenumber.appspot.com/phonenumberparser?number=%2B994+992123456

**Pull request closed without merging**
