### PR TITLE
Add cmake support for latest versions of protobuf

### PR DESCRIPTION
**Pull request by Tylerian**
Latest version of protobuf uses C++11 features like `constexpr` thus causing CMake to fail when trying to compile protobuf generated files.

### CODE REVIEW

**Comment by Tylerian** [comment]
I've signed it.

**Comment by Andhinilarasati** [comment]
comid keren

**Comment by gvollant** [comment]
if I understand, you expect compile libphonenumber with a C++ 98 compiler ? @Tylerian

**Comment by penmetsaa** [comment]
Hi,

In this (commit)[https://github.com/google/libphonenumber/commit/874af793779ee58b64d4d7dc302562751b33e58d] we are already bumped up the C++ version we need for compiling the project. So closing this PR.

**Pull request closed without merging**
