### PR TITLE
Small fixes to phonenumberutil.cc

### PR DESCRIPTION
**Pull request by lararennie**
Removing unused var, indent fix.

### CODE REVIEW

**Review by penmetsaa — APPROVED** [review]
My bad. Thanks Gilles and Lara.
I still did not get this error, I need to set different build / check options?

**Comment by lararennie** [comment]
> My bad. Thanks Gilles and Lara.
> I still did not get this error, I need to set different build / check options?

Did you get a warning?

**Comment by penmetsaa** [comment]
> > My bad. Thanks Gilles and Lara.
> > I still did not get this error, I need to set different build / check options?
> 
> Did you get a warning?

Nope :)

**Comment by gvollant** [comment]
Using clang-11 (from http://apt.llvm.org) on debian10, I cannot compile phonenumber 8.12.12 (see my comment at #2526), because it did not accept the warning.
Warning are different between compiler versions.

Note ; again, I'll be happy if anyone can take a look at #2482

**Comment by lararennie** [comment]
I merged a fix? Is it still broken for you?

Le sam. 7 nov. 2020 à 9:09 AM, Gilles Vollant <notifications@github.com> a
écrit :

**Pull request merged**
